---
title: "Untitled"
author: "Scott Bishop"
date: "November 4, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

# Install Packages
# ==================================================

packages <- c()   
init.pkg <- setdiff( packages, rownames( installed.packages() ) ) 

if ( length(init.pkg) > 0 ) 
{ 
    install.packages(init.pkg) 
} 

lapply(packages, require, character.only = TRUE)

```

```{r}

# Set Up Environment
# ==================================================

set.seed(19920917)

setwd('C:\\Users\\andre\\Desktop\\travelate\\R')
df <- read.csv('../data/hotels.csv')

```

```{r}

# Number of Hotel Names
nrow(unique(df["Hotel_Name"]))

# Export Hotel Frequency
hotel.names <- as.data.frame( table(df["Hotel_Name"]) )
hotel.names <- hotel.names[ order( hotel.names$Freq, decreasing = TRUE ), c(1,2) ]

write.csv( hotel.names, file = "../data/hotels_names.csv" )

```


```{r}

# Select Vaiables of Interest
# ==================================================
df <- subset(df, select = -c( Additional_Number_of_Scoring,
                              Review_Date,
                              Reviewer_Nationality,
                              Review_Total_Negative_Word_Counts,
                              Review_Total_Positive_Word_Counts,
                              Total_Number_of_Reviews_Reviewer_Has_Given,
                              lat,
                              lng ))

```

```{r}

# Normalize Average_Score and Reviewer_Score
df["Average_Score"]  <- round( ( df["Average_Score"] / 10 ), 2 ) 
df["Reviewer_Score"] <- round( ( df["Reviewer_Score"] / 10 ), 2 ) 

```

```{r}

# Transform days_since_review to Integer
df["days_since_review"] <- as.integer( unlist( df["days_since_review"] ) )

```

```{r}

# Transform Tags Variable into Array
tags <- as.character( unlist( df["Tags"] ) )
tags <- strsplit( tags, "[ ',]" )

remove <- c("", "[", "]", NA)

df["Tags"] <- as.character( unlist( df["Tags"] ) )

for ( i in 1:length( tags ) ) 
{
    df[i, "Tags"] <- paste( subset( tags[[i]], 
                            !(tags[[i]] %in% remove ) ), collapse = " " )
    
    if (i %% 1000 == 0) { print( i ) }
}

```

```{r}

# Write Updated CSV
write.csv( df, file = "../data/hotels_2.csv" )

```

```{r}

# Get Frequency of Countries

countries <- rep( '', nrow(df) )

for ( row in 1:nrow(df) )
{
    iter           <- strsplit(as.character( df[row, 1] ), " ")
    iter           <- unlist( iter )
    countries[row] <- iter[ length( iter ) ]
}

```

```{r}

# Write Country distribution to CSV
write.csv( as.data.frame(table(countries)), file = "../data/countries.csv" )

```

```{r}

temp.df <- read.csv('../data/hotels_2.csv')
temp.df <- temp.df[, -1]

temp.countries <- rep( '', nrow(temp.df) )

for ( row in 1:length(temp.countries) )
{
    iter                <- strsplit(as.character( temp.df[row, 1] ), " ")
    iter                <- unlist( iter )
    temp.countries[row] <- iter[ length( iter ) ]
}

temp.df.2 <- cbind(temp.countries, temp.df)

netherlands.df <- temp.df.2[ temp.df.2 == "Netherlands", ]
austria.df     <- temp.df.2[ temp.df.2 == "Austria", ]
france.df      <- temp.df.2[ temp.df.2 == "France", ]
italy.df       <- temp.df.2[ temp.df.2 == "Italy", ]
kingdom.df     <- temp.df.2[ temp.df.2 == "Kingdom", ]
spain.df       <- temp.df.2[ temp.df.2 == "Spain", ]

netherlands.df <- netherlands.df[ sample( nrow(netherlands.df), 10000 ), ]
austria.df     <- austria.df    [ sample( nrow(austria.df),     10000 ), ]
france.df      <- france.df     [ sample( nrow(france.df),      10000 ), ]
italy.df       <- italy.df      [ sample( nrow(italy.df),       10000 ), ]
kingdom.df     <- kingdom.df    [ sample( nrow(kingdom.df),     10000 ), ]
spain.df       <- spain.df      [ sample( nrow(spain.df),       10000 ), ]

temp.df.3 <- rbind(netherlands.df, austria.df, france.df, italy.df, kingdom.df, spain.df )
temp.df.3 <- temp.df.3[ sample( nrow(temp.df.3), nrow(temp.df.3) ), ]

colnames(temp.df.3) <- c('Hotel Address', 'Tags', 'Reviewer Score', 'Country', 'Total Reviews', 
                         'Hotel Name', 'Average Score', 'Negative Review', 'Positive Review', 'Days Since Review')
write.csv( temp.df.3, file = "../data/hotels_3.csv", row.names = FALSE )

```

```{r}

sentiment.df <- read.csv('../data/hotels_3_with_review_score.csv')

```

```{r}

neg.omit.array <- c('no', 'no negative', 'none', 'nothing', 'nil', 'nothing really', 'n a', 'na', 'nothing to say')
pos.omit.array <- c('no', 'no positive', 'none', 'nothing', 'nil', 'nothing really', 'n a', 'na', 'nothing to say')

temp.df.3[, 'Negative_Review'] <- tolower( as.character( temp.df.3[, 'Negative_Review'] ) )
temp.df.3[, 'Positive_Review'] <- tolower( as.character( temp.df.3[, 'Positive_Review'] ) )

for ( i in 1:nrow(temp.df.3) ) 
{
    if ( any( temp.df.3[i, 'Negative_Review'] == neg.omit.array ) )
    {
        temp.df.3[i, 'Negative_Review'] <- ''
    }
    
    if ( any( temp.df.3[i, 'Positive_Review'] == pos.omit.array ) )
    {
        temp.df.3[i, 'Positive_Review'] <- ''
    }
}

```

